version: '2.1'
services:
  unbound:
    build:
      context: .
    container_name: unbound
    ports:
      - "853:53/udp"
    command: -d -v
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2100:1800:6390:845f::10
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2100:1800:6390:845f::/80
        gateway: 2100:1800:6390:845f::1
